### ISSUE TITLE
Bug lors de la première utilisation

### ISSUE THREAD

**Issue by broncowdd** [yosko/jotter#1]
Salut mon pote, 
J'ai un bug juste après l'installation et la première connexion; comme je n'ai pas le temps de me pencher dessus (je suis au boulot) je te mets directement la capture d'écran.
http://files.warriordudimanche.net/index.php?f=528b71ca5c04b

A+ tard ;)

**Comment by yosko** [comment]
Ah oui, d'habitude je développe toujours avec l'affichage forcé des warning et là j'ai oublié. Visiblement y'en a quelques-uns qui trainent, et peut-être des erreurs au milieu ? ^^'
Je vais tenter de traquer ça...

**Edit 16h :** j'en ai corrigé l'essentiel dans ma version de dev.
- le foreach, mkdir et les "non-static" methods, ça trainait bêtement...
- les session start et header resent, je n'ai pas reproduit et ne comprend pas trop d'où ça vient... Je vais faire des tests plus poussés avec un log complet.
- fopen du .ses et opendir : j'avais oublié de créer le dossier "cache" à la racine pour les sessions. Tu peux le créer toi-même en attendant une correction. Pour les fwrite/fclose, je dois manquer un peu de contrôles...

**Comment by broncowdd** [comment]
autant de bugs que je connais bien ;-) _complicité de dev inside_ ^^

**Comment by yosko** [comment]
Je ferme car à priorio l'essentiel est corrigé. Si tu en trouves d'autres, tu pourrais réouvrir (ou faire un nouveau ticket).
