### ISSUE TITLE
petit bug css

### ISSUE THREAD

**Issue by broncowdd** [yosko/jotter#3]
Salut mon pote ;)
J'ai noté un petit bug css sur la toolbar: elle couvre une partie des outils:
![jotter0](https://f.cloud.github.com/assets/4249696/1643651/4a00915e-58ce-11e3-921b-5963e520d53c.PNG)

![jotter2](https://f.cloud.github.com/assets/4249696/1643653/53578b0e-58ce-11e3-9d41-1c1544bca368.PNG)

Je n'ai pas trop approfondi, mais on peut la rendre invisible si elle n'est pas utile ou même la positioner en fixed avec top:0 genre ça
![jotter1](https://f.cloud.github.com/assets/4249696/1643658/79854ae6-58ce-11e3-8725-a279f00c4598.PNG)

Toutefois, je pense que tu trouveras un truc plus propre ^^ Si j'avais un moment, j'approfondirais pour te proposer une solution clé en main... if only ^^

Sinon, c'est tiptop, par exemple pour gérer les idées de projets ^^ (J'EN AI PLEIN ! Argh !)
Encore merci ;)

**Comment by yosko** [comment]
Euh, elle n'est pas sensée s'afficher là xD
- Tu testes sur la version que j'ai mis à dispo hier soir (v0.3) ou la précédente (v0.2) ?
- Et t'es sur quel navigateur ?

J'avoue n'avoir testé pour l'instant que sur Windows/Firefox, mais il serait temps que je m'intéresse aux autres navigateurs modernes... ^^'

PS : moi je m'en sers pour mes travaux d'écriture et pour faire des listes. Pour les projets, j'ai déjà un MyTinyTodo :P

**Comment by broncowdd** [comment]
Je viens de la télécharger l'installer... donc c'est la dernière version.
Le bug ne se manifeste que sous chromium, sous firefox, tout va bien (j'aurais dû le préciser...)

**Comment by yosko** [comment]
Je m'en doutais un peu de toute façon. Mais faut que je fasse attention à Chrome/Chromium, parce qu'ils sont au moins autant utilisés... ^^'
Je regarde dès que possible, et intègrerai ça dans la v0.4 qui apportera la désactivation possible du Wysiwyg.

PS : hihi, je ne reproduis pas sur Chromium 33 version portable.. >.< Je testerai avec Chrome à la maison (impossible de l'installer à cause du proxy du boulot).

**Comment by broncowdd** [comment]
chez moi c'est chromium 25.0.1335.0
^^

**Comment by broncowdd** [comment]
J'ai vu que tu utilises flexbox: je ne connais pas bien, mais il y a peut-être un problème avec chrome dans cette version ?

**Comment by broncowdd** [comment]
Bon, c'est ça ! Chromium est un peu ancien et flex n'est pris en compte qu'à partir de v29 de chrome. Après test sous chrome (berk) version à jour, pas de soucis...

**Comment by yosko** [comment]
Ah j'aurais dû m'en douté que c'était les flexbox. Mets à jour Chromium, plutôt que Chrome ;)

Les flexbox sont un peu inévitable pour le layout envisagé. Jotter nécessite de supporter HTML5 (je vais le préciser dans les prérequis, tiens). Donc à moins que tu ne penses nécessaire de supporter les vieilles versions de Chrom(e|ium) et que tu n'ai une idée pour obtenir le même effet, je ferme en "wontfix".

**Comment by broncowdd** [comment]
pas de soucis, je suis en train de mettre chromium à jour ;)
A+
